branches: 
  - candidate
  - release-drafter
categories:
  - title: '🚀 Features'
    label: feature
  - title: '🎨 Enhancements'
    label: enhancement
  - title: '🐛 Bug Fixes'
    label: bug
  - title: '🔧 Under the hood'
    labels:
      - debt
			- dependencies
change-template: "* $TITLE (#$NUMBER)"
template: |
  ## What’s changed in ANET

  $CHANGES
