language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

notifications:
    slack: nci-agency:TvRV22whtaRGflaCPPfv2G1v

before_install:
  - docker run --name mssql-server -v ${PWD}:/hostdata -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd" -e "DB_NAME=testAnet" -e "DB_USER=anetUser" -e "DB_USER_PASSWORD=P@ssw0rd" -d -p 1433:1433 ncia/anet-mssql-linux
  - nvm install node
  - nvm use node
  - |
    cat <<EOF > localSettings.gradle
    run.environment("DB_DRIVER","sqlserver")
    run.environment("ANET_DB_SERVER","localhost")
    run.environment("ANET_DB_NAME","testAnet")
    run.environment("ANET_DB_USERNAME","sa")
    run.environment("ANET_DB_PASSWORD","P@ssw0rd")
  EOF

#By default travis runs gradle assemble in install. This is too early as we don't want to build yet
install:
  - cd client
  - npm install
  - cd ..

script:
  - cd client
  - npm run build
  - cd ..
  - ./gradlew dbMigrate
  - docker exec -ti mssql-server /opt/mssql-tools/bin/sqlcmd -S localhost -U anetUser -P P@ssw0rd -d testAnet -i /hostdata/insertBaseData.sql
  - ./gradlew check

after_script:
  - docker logs mssql-server
