language: java

jdk:
  - oraclejdk8

env:
  global:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=P@ssw0rd

before_install:
  - nvm install node
  - nvm use node
  - cd client
  - npm install
  - npm run build
  - cd ..
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server.list | sudo tee /etc/apt/sources.list.d/mssql-server.list
  - sudo apt-get update 
  - sudo apt-get install -y mssql-server
  - sudo apt-get install -y mssql-server-fts
  - touch localSettings.gradle
  - echo run.environment("DB_DRIVER","sqlserver") >> localSettings.gradle
  - echo run.environment("ANET_DB_SERVER","localhost")  >> localSettings.gradle
  - echo run.environment("ANET_DB_NAME","testanet") >> localSettings.gradle
  - echo run.environment("ANET_DB_USERNAME","SA") >> localSettings.gradle
  - echo run.environment("ANET_DB_PASSWORD","P@ssw0rd") >> localSettings.gradle
  - ./gradlew dbMigrate

