developmentMode: true

smtp:
  hostname: ${ANET_SMTP_SERVER}
  port: 25
  username: ${ANET_SMTP_USERNAME}
  password: ${ANET_SMTP_PASSWORD}
  startTLS: true
emailFromAddr: hunter+anet@dds.mil

database:
  driverClass: ${ANET_DB_DRIVER}
  user: ${ANET_DB_USERNAME}
  password: ${ANET_DB_PASSWORD}
  url: ${ANET_DB_URL}
  properties:
   date_string_format: ${ANET_DB_DATE_STRING_FORMAT}
   date_class: ${ANET_DB_DATE_CLASS}
waffleConfig:
  principalFormat: fqn
  roleFormat: both
  allowGuestLogin: false
  impersonate: false
  securityFilterProviders: waffle.servlet.spi.BasicSecurityFilterProvider
  #securityFilterProviders: "waffle.servlet.spi.BasicSecurityFilterProvider waffle.servlet.spi.NegotiateSecurityFilterProvider"
  #"waffle.servlet.spi.NegotiateSecurityFilterProvider/protocols": Negotiate NTLM
  "waffle.servlet.spi.BasicSecurityFilterProvider/realm": ANET


server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

views:
  .ftl:
    number_format: computer

logging:
  level: INFO
  loggers:
    "io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper" : DEBUG
    "org.skife.jdbi.v2.DBI" : INFO
    "org.sqlite.JDBC" : INFO
    "io.dropwizard.assets.AssetsBundle" : TRACE
    "io.dropwizard.assets.*" : TRACE
    "waffle.servlet.NegotiateSecurityFilter" : TRACE
    "mil.dds.anet.auth.AnetAuthenticationFilter" : TRACE
    "mil.dds.anet.AnetEmailWorker" : DEBUG
    "mil.dds.anet.resources.TestingResource" :
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/testingLogger.log
          archivedLogFilenamePattern: ./logs/testingLogger-%d.log.gz
          archivedFileCount: 2
  appenders:
    - type: console
      threshold: TRACE
      target: stdout
